services:
  controller:
    build: ./controller
    container_name: controller
    restart: unless-stopped
    env_file: .env
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    expose:
      - "3000"

  webapp:
    build: ./webapp
    container_name: webapp
    ports:
      - "80:80"
    depends_on:
      - controller
    restart: unless-stopped
    env_file: .env
