volumes:
  webapp-certbot:
  webapp-data:

services:
  frontend:
    build:
      context: ./frontend
      args:
        HOSTNAME: ${HOSTNAME:?}
        USER_ID: ${USER_ID:?}
    depends_on:
      - controller
      - webapp
    restart: unless-stopped
    environment:
      HOSTNAME: ${HOSTNAME:?}
      TZ: ${TZ:-UTC}
      PORT: 5173
      USER_ID: ${USER_ID:?}
    # volumes:
    #   - .:/app # TODO: CHECKfor development
    ports:
      - "5173:5173"
  webapp:
    build:
      context: ./webapp
      args:
        HOSTNAME: ${HOSTNAME:?}
    depends_on:
      - controller
    restart: unless-stopped
    environment:
      HOSTNAME: ${HOSTNAME:?}
      CUSTOM_USER_ID: ${CUSTOM_USER_ID:-}
      TZ: ${TZ:-UTC}
      PORT: 80
    volumes:
      - webapp-certbot:/etc/letsencrypt
      - webapp-data:/data
      # - .:/app # TODO: CHECKfor development
    ports:
      - "80:80"
  controller:
    build: ./controller
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
      PORT: 3000
      FLAG: ${FLAG:?}
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      # - "./ctfs:/ctfs:ro"
      # - type: bind
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock
    expose:
      - "3000"
