volumes:
  webapp-certbot:
  webapp-data:

services:
  webapp:
    build:
      context: ./webapp
      args:
        HOSTNAME: ${HOSTNAME:?}
    depends_on:
      - controller
    restart: unless-stopped
    environment:
      HOSTNAME: ${HOSTNAME:?}
      CUSTOM_USER_ID: ${CUSTOM_USER_ID:-}
      TZ: ${TZ:-UTC}
    volumes:
      - webapp-certbot:/etc/letsencrypt
      - webapp-data:/data
    ports:
      - 80:80
      - 443:443
  controller:
    build: ./controller
    user: "${CONTROLLER_UID:?}:${CONTROLLER_GID:?}"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - "./ctfs:/ctfs:ro"
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    expose:
      - "3000"
