volumes:
  webapp-certbot:
  webapp-data:

services:
  frontend:
    build:
      context: ./frontend
      args:
        HOSTNAME: ${HOSTNAME:?}
    depends_on:
      - controller
      - webapp
    restart: unless-stopped
    environment:
      HOSTNAME: ${HOSTNAME:?}
      CUSTOM_USER_ID: ${CUSTOM_USER_ID:-}
      TZ: ${TZ:-UTC}
      PORT: 5173
    # volumes:
    #   - .:/app # TODO: CHECKfor development
    ports:
      - "5173:5173"
  webapp:
    build:
      context: ./webapp
      args:
        HOSTNAME: ${HOSTNAME:?}
    depends_on:
      - controller
    restart: unless-stopped
    environment:
      HOSTNAME: ${HOSTNAME:?}
      CUSTOM_USER_ID: ${CUSTOM_USER_ID:-}
      TZ: ${TZ:-UTC}
      PORT: 80
    volumes:
      - webapp-certbot:/etc/letsencrypt
      - webapp-data:/data
      # - .:/app # TODO: CHECKfor development
    ports:
      - "80:80"
  controller:
    build: ./controller
    user: "${CONTROLLER_UID:?}:${CONTROLLER_GID:?}"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
      PORT: 3000
    volumes:
      - "./ctfs:/ctfs:ro"
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    expose:
      - "3000"
