volumes:
  controller-config:

services:
  controller:
    build: ./controller
    container_name: controller
    restart: unless-stopped
    volumes:
      - controller-config:/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    expose:
      - "3000"

  webapp:
    build: ./webapp
    container_name: webapp
    ports:
      - "80:80"
    depends_on:
      - controller
    restart: unless-stopped
